export const LOAD_AGENCIES_SUCCESS = "LOAD_AGENCIES_SUCCESS";

export const LOAD_AGENCIES_CAR_SPOT = "LOAD_AGENCIES_CAR_SPOT";
export const LOAD_AGENCIES_BIKE_SPOT = "LOAD_AGENCIES_BIKE_SPOT";

export const SAVE_CAR_BOOKING = "SAVE_CAR_BOOKING";
export const SAVE_BIKE_BOOKING = "SAVE_BIKE_BOOKING";

export const UPDATE_CAR_BOOKING = "UPDATE_CAR_BOOKING";
export const UPDATE_BIKE_BOOKING = "UPDATE_BIKE_BOOKING";
